In [4]:
import PIL
from PIL import Image
import pandas as pd
import numpy as np
import time
from pathlib import Path
import os
import shutil

from sklearn.cross_validation import StratifiedShuffleSplit

In [25]:
# Read customer genres from file
y = pd.read_csv("y.csv", sep=',')
y = y.converted.values
y

array(['AcCrTh', 'AcCrTh', 'Ho', ..., 'RoCoDa', 'Ot', 'Ot'], dtype=object)

In [26]:
#Split data to train and test
sss1 = StratifiedShuffleSplit(y, 1, test_size=0.20)

In [27]:
for train_index, test_index in sss1:
    full_training_index = train_index
    testing_index = test_index
    
print(len(full_training_index))
print(len(testing_index))

14827
3707


In [28]:
#Split Train data further into train and validation
sss2 = StratifiedShuffleSplit(y[full_training_index], 1, test_size=0.20)

for train_index, test_index in sss2:
    training_index = full_training_index[train_index]
    validating_index = full_training_index[test_index]

In [29]:
print(len(training_index))
print(len(validating_index))
print(len(testing_index))

11862
2965
3707


In [30]:
#Convert Classes to integers
y_map = pd.DataFrame(sorted(np.unique(y)))
y_map.columns = ['genre']
y_map['class'] = y_map.index

y_df = pd.DataFrame(y)
y_df.columns = ['genre']
y = y_df.join(y_map.set_index('genre'), on = 'genre')['class'].values

del y_df

In [31]:
y_map

genre  class
0  AcAdDr      0
1  AcCrTh      1
2  AcThMi      2
3  CoFaDr      3
4      Ho      4
5      Ot      5
6  RoCoDa      6
7    ScFa      7

In [32]:
# Validate data splits
print(y[training_index].shape)
print(y[validating_index].shape)
print(y[testing_index].shape)

u, unique_counts  = np.unique(y, return_counts = True)
print(u)
print(unique_counts)

u, unique_counts  = np.unique(y[training_index], return_counts = True)
print(u)
print(unique_counts)

u, unique_counts  = np.unique(y[validating_index], return_counts = True)
print(u)
print(unique_counts)

u, unique_counts  = np.unique(y[testing_index], return_counts = True)
print(u)
print(unique_counts)

(11862L,)
(2965L,)
(3707L,)
[0 1 2 3 4 5 6 7]
[1313 4214 1345  314 1416 1131 8137  664]
[0 1 2 3 4 5 6 7]
[ 840 2697  861  201  906  724 5208  425]
[0 1 2 3 4 5 6 7]
[ 210  674  215   50  227  181 1302  106]
[0 1 2 3 4 5 6 7]
[ 263  843  269   63  283  226 1627  133]


In [24]:
y[12]

4

In [33]:
# Move data from posters folder to train, validation, and test and then further to the class folder to which the image belongs
for i in range(len(y)):
    source_img = './posters/poster_' + str(i) + '.jpeg'
    
    if i in training_index:
        destination_path = './data/train/' + str(y[i])
    elif i in validating_index:
        destination_path = './data/validation/' + str(y[i])
    elif i in testing_index:
        
        destination_path = './data/test/' + str(y[i])
    else:
        print i, y[i]
        destination_path = './data/'

    shutil.copy2(source_img, destination_path)

In [21]:
training_index

array([12753, 14475,  5024, ...,  9443,  9501,  4688], dtype=int64)

In [24]:
list(set(training_index).intersection(validating_index))

[]